# Generated by Django 4.1.1 on 2022-09-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_checkout', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
